# Generated by Django 4.2.13 on 2024-06-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_excerpt_post_update_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='update_on',
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(),
        ),
    ]
