# Generated by Django 4.2.13 on 2024-06-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_rename_updates_on_about_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='content',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
